### ISSUE TITLE
Unreliable reward payment

### ISSUE THREAD

**Issue by alepacheco** [EOSBlox/blox-tictactoe-stakes#1]
The loser and change its permissions mid game making the game stakeless 

https://github.com/EOSBlox/blox-tictactoe-stakes/blob/6c7f97cbf75abcc832a4faa2f2671335c1c0c363/TicTacToe.cpp#L120

**Comment by netromdk** [comment]
Thanks for the notice. I am going to try making another version where the stakes are transferred from both players on `newgame` to make sure they have the funds, and then transfer from the contract to the winner instead (and on draw or endgame to both, of course).

**Comment by netromdk** [comment]
@alepacheco I've changed in accordance to the above. Any comments?
